# Generated by Django 2.1.7 on 2019-04-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCenter', '0002_disciplines_levels_teachers_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.Disciplines')),
                ('levelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.Levels')),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.Teachers')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.Types')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.Courses')),
            ],
        ),
    ]
