# Generated by Django 2.1.7 on 2019-04-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCenter', '0004_auto_20190405_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кількість академічних годин'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='pages',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кількість сторінок інструкцій'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='teacherId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCenter.Teachers'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кількість академічних годин'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Зміст теми'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='pages',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кількість сторінок інструкцій'),
        ),
    ]
